import type {
  User,
  Wallet,
  BankAccount,
  Transaction,
  Contact,
  MerchantUser,
  AdminApproval,
  SpendingCategory,
  MonthlyData,
  PaymentRequest,
} from "./types"

export const currentUser: User = {
  id: "usr_001",
  name: "Alex Johnson",
  email: "alex@finewallet.com",
  phone: "+1 (555) 123-4567",
  avatar: "",
  kycStatus: "not_started",
  pinSet: true,
  createdAt: "2024-06-15",
}

export const wallet: Wallet = {
  id: "wal_001",
  userId: "usr_001",
  balance: 6235.0,
  isActive: true,
  currency: "USD",
}

export const bankAccounts: BankAccount[] = [
  {
    id: "ba_001",
    userId: "usr_001",
    bankName: "Chase Bank",
    accountNumber: "****4829",
    routingNumber: "021000021",
    holderName: "Alex Johnson",
    accountType: "checking",
    last4: "4829",
    isVerified: true,
    isPrimary: true,
    bankLogo: "C",
  },
  {
    id: "ba_002",
    userId: "usr_001",
    bankName: "Bank of America",
    accountNumber: "****7312",
    routingNumber: "026009593",
    holderName: "Alex Johnson",
    accountType: "savings",
    last4: "7312",
    isVerified: true,
    isPrimary: false,
    bankLogo: "B",
  },
  {
    id: "ba_003",
    userId: "usr_001",
    bankName: "Wells Fargo",
    accountNumber: "****0485",
    routingNumber: "121000248",
    holderName: "Alex Johnson",
    accountType: "checking",
    last4: "0485",
    isVerified: true,
    isPrimary: false,
    bankLogo: "W",
  },
]

export const contacts: Contact[] = [
  {
    id: "ct_001",
    name: "David Warner",
    email: "david.warner@email.com",
    avatar: "",
    lastTransactionDate: "2026-02-18",
  },
  {
    id: "ct_002",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    avatar: "",
    lastTransactionDate: "2026-02-15",
  },
  {
    id: "ct_003",
    name: "Marcus Rivera",
    email: "marcus.r@email.com",
    avatar: "",
    lastTransactionDate: "2026-02-10",
  },
  {
    id: "ct_004",
    name: "Emily Brooks",
    email: "emily.b@email.com",
    avatar: "",
    lastTransactionDate: "2026-01-28",
  },
  {
    id: "ct_005",
    name: "James Okoro",
    email: "james.okoro@email.com",
    avatar: "",
    lastTransactionDate: "2026-01-20",
  },
]

export const transactions: Transaction[] = [
  {
    id: "tx_001",
    type: "send",
    amount: 350.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "david.warner@email.com",
    recipientName: "David Warner",
    senderName: "Alex Johnson",
    bankAccountId: "ba_001",
    category: "Transfer",
    status: "completed",
    note: "Rent share",
    createdAt: "2026-02-18T14:30:00Z",
    requiresPin: false,
  },
  {
    id: "tx_002",
    type: "receive",
    amount: 1200.0,
    currency: "USD",
    senderEmail: "sarah.chen@email.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "Alex Johnson",
    senderName: "Sarah Chen",
    category: "Salary",
    status: "completed",
    note: "Freelance payment",
    createdAt: "2026-02-15T09:00:00Z",
    requiresPin: false,
  },
  {
    id: "tx_003",
    type: "send",
    amount: 12.56,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "store@apple.com",
    recipientName: "Apple Store",
    senderName: "Alex Johnson",
    category: "Shopping",
    status: "completed",
    createdAt: "2026-02-14T12:45:00Z",
    requiresPin: false,
  },
  {
    id: "tx_004",
    type: "send",
    amount: 35.56,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "billing@netflix.com",
    recipientName: "Netflix",
    senderName: "Alex Johnson",
    category: "Entertainment",
    status: "completed",
    createdAt: "2026-02-14T12:45:00Z",
    requiresPin: false,
  },
  {
    id: "tx_005",
    type: "top_up",
    amount: 2000.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "My Wallet",
    senderName: "Alex Johnson",
    bankAccountId: "ba_001",
    category: "Top Up",
    status: "completed",
    createdAt: "2026-02-10T08:00:00Z",
    requiresPin: true,
  },
  {
    id: "tx_006",
    type: "send",
    amount: 750.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "marcus.r@email.com",
    recipientName: "Marcus Rivera",
    senderName: "Alex Johnson",
    bankAccountId: "ba_002",
    category: "Transfer",
    status: "completed",
    note: "Project payment",
    createdAt: "2026-02-08T16:20:00Z",
    requiresPin: true,
  },
  {
    id: "tx_007",
    type: "receive",
    amount: 500.0,
    currency: "USD",
    senderEmail: "emily.b@email.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "Alex Johnson",
    senderName: "Emily Brooks",
    category: "Transfer",
    status: "completed",
    note: "Birthday gift",
    createdAt: "2026-02-05T11:00:00Z",
    requiresPin: false,
  },
  {
    id: "tx_008",
    type: "send",
    amount: 89.99,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "store@amazon.com",
    recipientName: "Amazon",
    senderName: "Alex Johnson",
    category: "Shopping",
    status: "completed",
    createdAt: "2026-02-03T15:30:00Z",
    requiresPin: false,
  },
  {
    id: "tx_009",
    type: "send",
    amount: 45.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "restaurant@grubhub.com",
    recipientName: "GrubHub",
    senderName: "Alex Johnson",
    category: "Food & Dining",
    status: "completed",
    createdAt: "2026-02-01T19:45:00Z",
    requiresPin: false,
  },
  {
    id: "tx_010",
    type: "send",
    amount: 600.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "james.okoro@email.com",
    recipientName: "James Okoro",
    senderName: "Alex Johnson",
    bankAccountId: "ba_001",
    category: "Transfer",
    status: "pending",
    note: "Equipment purchase",
    createdAt: "2026-01-28T10:15:00Z",
    requiresPin: true,
  },
  {
    id: "tx_011",
    type: "receive",
    amount: 3200.0,
    currency: "USD",
    senderEmail: "payroll@company.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "Alex Johnson",
    senderName: "Company Payroll",
    category: "Salary",
    status: "completed",
    createdAt: "2026-01-25T09:00:00Z",
    requiresPin: false,
  },
  {
    id: "tx_012",
    type: "send",
    amount: 120.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "utility@electricco.com",
    recipientName: "Electric Co.",
    senderName: "Alex Johnson",
    category: "Utilities",
    status: "completed",
    createdAt: "2026-01-22T14:00:00Z",
    requiresPin: false,
  },
  {
    id: "tx_013",
    type: "send",
    amount: 250.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "sarah.chen@email.com",
    recipientName: "Sarah Chen",
    senderName: "Alex Johnson",
    category: "Transfer",
    status: "failed",
    note: "Concert tickets",
    createdAt: "2026-01-20T18:30:00Z",
    requiresPin: false,
  },
  {
    id: "tx_014",
    type: "top_up",
    amount: 1500.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "My Wallet",
    senderName: "Alex Johnson",
    bankAccountId: "ba_002",
    category: "Top Up",
    status: "completed",
    createdAt: "2026-01-18T08:00:00Z",
    requiresPin: true,
  },
  {
    id: "tx_015",
    type: "send",
    amount: 28.5,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "store@spotify.com",
    recipientName: "Spotify",
    senderName: "Alex Johnson",
    category: "Entertainment",
    status: "completed",
    createdAt: "2026-01-15T12:00:00Z",
    requiresPin: false,
  },
  {
    id: "tx_016",
    type: "receive",
    amount: 175.0,
    currency: "USD",
    senderEmail: "marcus.r@email.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "Alex Johnson",
    senderName: "Marcus Rivera",
    category: "Transfer",
    status: "completed",
    note: "Split dinner",
    createdAt: "2026-01-12T20:00:00Z",
    requiresPin: false,
  },
  {
    id: "tx_017",
    type: "send",
    amount: 1050.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "landlord@property.com",
    recipientName: "Property Management",
    senderName: "Alex Johnson",
    bankAccountId: "ba_001",
    category: "Rent",
    status: "completed",
    note: "January rent",
    createdAt: "2026-01-05T09:00:00Z",
    requiresPin: true,
  },
  {
    id: "tx_018",
    type: "send",
    amount: 65.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "gym@fitlife.com",
    recipientName: "FitLife Gym",
    senderName: "Alex Johnson",
    category: "Health & Fitness",
    status: "completed",
    createdAt: "2026-01-03T07:30:00Z",
    requiresPin: false,
  },
  {
    id: "tx_019",
    type: "withdrawal",
    amount: 500.0,
    currency: "USD",
    senderEmail: "alex@finewallet.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "Chase Bank ****4829",
    senderName: "Alex Johnson",
    bankAccountId: "ba_001",
    category: "Withdrawal",
    status: "completed",
    createdAt: "2026-01-01T10:00:00Z",
    requiresPin: true,
  },
  {
    id: "tx_020",
    type: "receive",
    amount: 420.0,
    currency: "USD",
    senderEmail: "james.okoro@email.com",
    recipientEmail: "alex@finewallet.com",
    recipientName: "Alex Johnson",
    senderName: "James Okoro",
    category: "Transfer",
    status: "completed",
    note: "Consulting fee",
    createdAt: "2025-12-28T14:00:00Z",
    requiresPin: false,
  },
]

export const spendingCategories: SpendingCategory[] = [
  { name: "Transfer", amount: 2000, color: "var(--chart-1)", percentage: 35 },
  { name: "Shopping", amount: 1200, color: "var(--chart-2)", percentage: 21 },
  { name: "Rent", amount: 1050, color: "var(--chart-3)", percentage: 18 },
  { name: "Entertainment", amount: 650, color: "var(--chart-4)", percentage: 11 },
  { name: "Food & Dining", amount: 480, color: "var(--chart-5)", percentage: 8 },
  { name: "Utilities", amount: 400, color: "var(--color-muted-foreground)", percentage: 7 },
]

export const monthlyData: MonthlyData[] = [
  { month: "Sep", income: 4200, expense: 3100 },
  { month: "Oct", income: 3800, expense: 2900 },
  { month: "Nov", income: 5100, expense: 3500 },
  { month: "Dec", income: 4500, expense: 4100 },
  { month: "Jan", income: 4875, expense: 3578 },
  { month: "Feb", income: 5395, expense: 2883 },
]

export const merchants: MerchantUser[] = [
  {
    id: "mrc_001",
    businessName: "Urban Coffee House",
    email: "admin@urbancoffee.com",
    status: "active",
    totalRevenue: 45230.0,
    qrCode: "UCH-QR-001",
    createdAt: "2024-03-10",
  },
  {
    id: "mrc_002",
    businessName: "TechGear Store",
    email: "payments@techgear.io",
    status: "active",
    totalRevenue: 128750.0,
    qrCode: "TGS-QR-002",
    createdAt: "2024-05-22",
  },
  {
    id: "mrc_003",
    businessName: "Fresh Bites Deli",
    email: "owner@freshbites.com",
    status: "pending",
    totalRevenue: 0,
    qrCode: "",
    createdAt: "2026-02-01",
  },
]

export const adminApprovals: AdminApproval[] = [
  {
    id: "apv_001",
    type: "kyc",
    userName: "Rachel Kim",
    userEmail: "rachel.k@email.com",
    details: "Government ID and selfie submitted for verification",
    status: "pending",
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "apv_002",
    type: "merchant",
    userName: "Fresh Bites Deli",
    userEmail: "owner@freshbites.com",
    details: "New merchant application - Restaurant category",
    status: "pending",
    createdAt: "2026-02-19T15:00:00Z",
  },
  {
    id: "apv_003",
    type: "large_transfer",
    userName: "Michael Torres",
    userEmail: "m.torres@email.com",
    details: "Transfer of $15,000 to external bank account",
    status: "pending",
    createdAt: "2026-02-18T09:30:00Z",
  },
  {
    id: "apv_004",
    type: "bank_account",
    userName: "Lisa Park",
    userEmail: "lisa.p@email.com",
    details: "Adding new bank account: Wells Fargo ****8821",
    status: "pending",
    createdAt: "2026-02-17T14:00:00Z",
  },
  {
    id: "apv_005",
    type: "kyc",
    userName: "Omar Hassan",
    userEmail: "omar.h@email.com",
    details: "KYC resubmission after initial rejection",
    status: "pending",
    createdAt: "2026-02-16T11:00:00Z",
  },
]

export const paymentRequests: PaymentRequest[] = [
  {
    id: "pr_001",
    fromName: "Sarah Chen",
    fromEmail: "sarah.chen@email.com",
    amount: 75.00,
    currency: "USD",
    note: "Dinner last Friday",
    status: "pending",
    createdAt: "2026-02-22T18:30:00Z",
  },
  {
    id: "pr_002",
    fromName: "Marcus Rivera",
    fromEmail: "marcus.r@email.com",
    amount: 120.00,
    currency: "USD",
    note: "Concert tickets",
    status: "pending",
    createdAt: "2026-02-21T14:00:00Z",
  },
  {
    id: "pr_003",
    fromName: "Emily Brooks",
    fromEmail: "emily.b@email.com",
    amount: 45.50,
    currency: "USD",
    note: "Uber ride split",
    status: "pending",
    createdAt: "2026-02-20T09:15:00Z",
  },
  {
    id: "pr_004",
    fromName: "James Okoro",
    fromEmail: "james.okoro@email.com",
    amount: 200.00,
    currency: "USD",
    note: "Group gift contribution",
    status: "pending",
    createdAt: "2026-02-19T11:00:00Z",
  },
]

export const supportedBanks = [
  "Chase Bank",
  "Bank of America",
  "Wells Fargo",
  "Citibank",
  "US Bank",
  "Capital One",
  "TD Bank",
  "PNC Bank",
  "Truist",
  "Fifth Third Bank",
]
